create table if not exists public.site_pages (
  id bigint generated by default as identity primary key,
  page_key text not null unique,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_pages enable row level security;

drop policy if exists "Public Can Read Site Pages" on public.site_pages;
create policy "Public Can Read Site Pages"
on public.site_pages for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated Admin Can Insert Site Pages" on public.site_pages;
create policy "Authenticated Admin Can Insert Site Pages"
on public.site_pages for insert
to authenticated
with check (true);

drop policy if exists "Authenticated Admin Can Update Site Pages" on public.site_pages;
create policy "Authenticated Admin Can Update Site Pages"
on public.site_pages for update
to authenticated
using (true)
with check (true);

create index if not exists site_pages_page_key_idx
on public.site_pages (page_key);

